threads:  # Number of threads to use

###################################################| rule FastQC |##################################################################

samples:  # List of sample prefixes
  - ""
  - ""
  - ""

raw_reads:   # Path to the directory with raw sequencing reads

##################################################| rule trimmomatic |##############################################################

trimmer:
  - "TRAILING:3"
  - "LEADING:3"
  - "MINLEN:100"
  - "SLIDINGWINDOW:4:28"  # Trimmomatic parameters

################################################| rule Hybpiper assemble |#########################################################
    
sample_names_file: ""           #text file with sample name (list of sample prefixes)
    
target_file: ""               #fasta file with reference set of genes 

aligner: ""                          #available aligners, select from diamond or bwa

diamond_sensitivity: ""  #{mid-sensitive,sensitive,more-sensitive,very-sensitive,ultra-sensitive} 

################################################| rule recovery heatmap |###########################################################

heatmap_filename: ""           #Name of the gene recovery heatmap

heatmap_filetype: ""                      # select from png, pdf, eps, tiff or svg

#####################################################| Path to tools |##############################################################

mafft_path: ""

catsequences_path: ""

iqtree_path: ""

seq_type: "dna" 

####################################################| rule Bootstrapping |##########################################################

bootstrap: ""   #yes or no

bootstrap_replicates: "1000" #No of bootstrap replicates (min recommended no. is 1000, and min sequences in alignment should be >=4)
